MP3/views/admin.py
import csv
import io
from flask import Blueprint, render_template, request, redirect, flash
from werkzeug.utils import secure_filename
from sql.db import DB
import traceback

admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route("/import", methods=["GET", "POST"])
def importCSV():
    if request.method == "POST":
        if 'file' not in request.files:
            return redirect(request.url)
        file = request.files['file']
        if file.filename == '':
            flash('No selected file', "warning")
            return redirect(request.url)
        
        # TODO importcsv-1: Check that it's a .csv file, return a proper flash message if it's not
        #rv437-29/11/23
        if file and secure_filename(file.filename):
            file_name = secure_filename(file.filename)
            if file_name.endswith('.csv'):
                organizations = []
                donations = []

                organization_query = """
                INSERT INTO IS601_MP3_Organizations (name, address, city, country, state, zip, website, description)
                VALUES (%(name)s, %(address)s, %(city)s, %(country)s, %(state)s, %(zip)s, %(website)s, %(description)s)
                ON DUPLICATE KEY UPDATE 
                    address=values(address),
                    city=values(city),
                    country=values(country),
                    state=values(state),
                    zip=values(zip),
                    website=values(website),
                    description=values(description)
                """

                donation_query = """
                INSERT INTO IS601_MP3_Donations (donor_firstname, donor_lastname, donor_email, item_name, item_description, item_quantity, organization_id, donation_date, comments)
                VALUES (%(donor_firstname)s, %(donor_lastname)s, %(donor_email)s, %(item_name)s, %(item_description)s, %(quantity)s, 
                        (SELECT id FROM IS601_MP3_Organizations WHERE name = %(organization_name)s LIMIT 1), 
                        %(donation_date)s, %(comments)s)
                ON DUPLICATE KEY UPDATE 
                    donor_firstname=%(donor_firstname)s,
                    donor_lastname=%(donor_lastname)s,
                    donor_email=%(donor_email)s,
                    item_name=%(item_name)s, 
                    item_quantity = %(quantity)s,
                    item_description= %(item_description)s,
                    comments=%(comments)s, 
                    organization_id = (SELECT id FROM IS601_MP3_Organizations WHERE name=%(organization_name)s LIMIT 1),
                    donation_date = %(donation_date)s,
                    comments=%(comments)s
                """

                try:
                    # Read the file as a stream
                    stream = io.TextIOWrapper(file.stream._file, "UTF8", newline=None)
                    
                    # TODO importcsv-2: Read the csv file stream as a dictionary
                     #rv437-29/11/23
                    csv_reader = csv.DictReader(stream)
                    
                    for row in csv_reader:
                        # TODO importcsv-3: Extract organization data and append to the organization list
                        # as a dictionary only with organization data if all organization fields are present
                         #rv437-29/11/23
                        if all(key in row for key in ['organization_name', 'organization_address', 'organization_city', 'organization_country', 'organization_state', 'organization_zip,', 'organization_website', 'organization_description']):
                            organizations.append({
                                'name': row['organization_name'],
                                'address': row['organization_address'],
                                'city': row['organization_city'],
                                'country': row['organization_country'],
                                'state': row['organization_state'],
                                'zip': row['organization_zip,'],
                                'website': row['organization_website'],
                                'description': row['organization_description'],
                            })

                        # TODO importcsv-4: Extract donation data and append to the donation list
                        # as a dictionary only with donation data if all donation fields are present
                         #rv437-29/11/23
                        if all(key in row for key in ['donor_firstname', 'donor_lastname', 'donor_email', 'item_name', 'item_description', 'quantity', 'organization_name', 'donation_date', 'comments']):
                            donations.append({
                                'donor_firstname': row['donor_name'].split()[0] if row["donor_name"] else '',
                                'donor_lastname': row['donor_name'].split()[1] if len(row["donor_name"].split())>1 else '',
                                'donor_email': row['donor_email'],
                                'item_name': row['item_name'],
                                'item_description': row['item_description'],
                                'quantity': row['quantity'],
                                'organization_name': row['organization_name'],
                                'donation_date': row['donation_date'],
                                'comments': row['comments'],
                            })
                        
                    if len(organizations) > 0:
                        print(f"Inserting or updating {len(organizations)} organizations")
                        try:
                            result = DB.insertMany(organization_query, organizations)
                            # TODO importcsv-5: Display a flash message about the number of organizations inserted
                             #rv437-29/11/23
                            flash(f"{len(organizations)} organizations inserted or updated", "success")
                        except Exception as e:
                            traceback.print_exc()
                            flash("There was an error loading in the CSV data for organizations", "danger")
                    else:
                        # TODO importcsv-6: Display a flash message (info) that no organizations were loaded
                         #rv437-29/11/23
                        flash("No organizations to import", "info")

                    if len(donations) > 0:
                        print(f"Inserting or updating {len(donations)} donations")
                        try:
                            result = DB.insertMany(donation_query, donations)
                            # TODO importcsv-7: Display a flash message about the number of donations loaded
                             #rv437-29/11/23
                            flash(f"{len(donations)} donations inserted or updated", "success")
                        except Exception as e:
                            traceback.print_exc()
                            flash("There was an error loading in the CSV data for donations", "danger")
                    else:
                        # TODO importcsv-8: Display a flash message (info) that no donations were loaded
                         #rv437-29/11/23
                        flash("No donations to import", "info")

                    try:
                        result = DB.selectOne("SHOW SESSION STATUS LIKE 'questions'")
                        print(f"Result {result}")
                    except Exception as e:
                        traceback.print_exc()
                        flash("There was an error counting session queries", "danger")
                        
                except Exception as e:
                    traceback.print_exc()
                    flash("There was an error processing the CSV file", "danger")
            else:
                flash("Select only csv files")

    return render_template("upload.html")

MP3/views/geography.py
import pycountry
import json
from flask import Blueprint, request

geo = Blueprint("geo", __name__, url_prefix='/geo')
# TODO DO NOT EDIT
# these are javascript endpoints used from country_state_selector.html
@geo.route("/countries")
def countries():
    # extract just the data we need for our <select> options
    countries = map(lambda c: {"code": c.alpha_2, "name": c.name},list(pycountry.countries))
    return json.dumps(list(countries))

@geo.route("/states")
def states():
    # extract just the data we need for our <select> options
    country_code = request.args.get("country_code", default="", type=str)
    states = []
    if country_code.strip():
        states = pycountry.subdivisions.get(country_code=country_code.strip())
    print(f"Found [{len(states)}] states for country_code [{country_code}]")
    if not states:
        states = []
    states = list(map(lambda s: {"name": s.name, "code": s.code.split("-")[1]}, 
        states))
    return json.dumps(states)

MP3/templates/country_state_selector.html
{# TODO DO NOT EDIT #}
{% macro country_state_selector(country="", state="", layout="vertical") %}
{% set c = request.args.get("country", request.form.get("country", country or '')) %}
{% set s = request.args.get("state", request.form.get("state", state or '')) %}
{% if layout and layout == 'horizontal' %}
{# version for filter forms #}
<div class="col">
    <label class="visually-hidden" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="col">
    <label class="visually-hidden" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}">
        <option value="">Select State...</option>
    </select>
</div>
{% else %}
{# version for add/edit forms #}
<div class="form-group mb-3">
    <label class="form-label" for="country">Country</label>
    <select name="country" id="country" class="form-select" value="{{c}}"
        required onchange="fetchStates(this.value)">
        <option value="">Select Country...</option>
    </select>
</div>
<div class="form-group mb-3">
    <label class="form-label" for="state">State</label>
    <select name="state" id="state" class="form-select" value="{{s}}" required>
        <option value="">Select State...</option>
    </select>
</div>
{% endif %}
<script>
    //gets called on page load and when the country selection changes
    const fetchStates = (country) => {
        //use jinja to return a string in the html template
        //this string will be as if we did let state = "whatever"
        let state = "{{s}}";
        console.log("fetching", country);
        fetch(`{{url_for('geo.states')}}?country_code=${country}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='state']");

                //if we had options, "clear" it to be the default option
                //so appending works
                if (ele.children.length > 1) {
                    ele.innerHTML = `<option value="">Select State...</option>`;
                }
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args state
                ele.value = state;
            });
    };
    window.addEventListener("load", () => {
        //use jinja to return a string in the html template
        //this string will be as if we did let country = "whatever"
        let country = "{{c}}";
        //get the country list from the endpoint
        fetch(`{{url_for('geo.countries')}}`)
            .then(resp => resp.json())
            .then(data => {
                let ele = document.querySelector("select[name='country']");
                ele.value = "";//clear the value so "onchange" works
                //dynamically create option tags
                for (let d of data) {
                    let nele = document.createElement("option");
                    nele.value = d.code;
                    nele.innerText = d.name;
                    ele.appendChild(nele);
                }
                //assign the default or args country
                ele.value = country;
            })
            .finally(() => {
                //get the state list from the endpoint
                fetchStates(country);
            });
    });
</script>
{% endmacro %}

MP3/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="h1 text-center text-warning">Thankful Donations</div>
    <div class="w-50 mx-auto bg-light text-center caption border">
        Thankful Donations: Helping organizations share with those in need.
    </div>
    <div class="lead text-center btyb">Brought to you by Rishitha (rv437) from
        section
        IS601-007
        {# TODO replace my name with your first name #}
        {# TODO replace my ucid with your ucid #}
        {# TODO replace 000 with your section (i.e., 005, 007, etc) #}
    </div>
</div>
{% endblock %}

MP3/templates/list_donations.html
{% extends "layout.html" %}
{% block title %}Donations{% endblock %}
{% block content %}
{% from "organization_dropdown.html" import organization_dropdown %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">{{organization_name}} Donations</div>
    <form method="GET">
        <div class="row">
            {# TODO
                build a horizontal filter/sort form with
                donor first name (show as first name, but name should be fn)
                donor last_name (show as last name, but name should be ln)
                donor email (validate as text, not email, so partial match works)
                item name
                organization (provided) (name is organization value is the id)
                sort/order (using allowed_columns and provided partial template)
                limit (default 10)
                ensure all fields prefill with request arg data if provided
                #}
    
                {#rv437-29/11/23#}
            <!-- Donor First Name -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="donor_firstname">Donor First Name</label>
                <input type="text" class="form-control" id="donor_firstname" name="donor_firstname"
                       value="{{ request.args.get('donor_firstname') or '' }}" placeholder="First Name">
            </div>

            <!-- Donor Last Name -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="donor_lastname">Donor Last Name</label>
                <input type="text" class="form-control" id="donor_lastname" name="donor_lastname"
                       value="{{ request.args.get('donor_lastname') or ''}}" placeholder="Last Name">
            </div>

            <!-- Donor Email -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="donor_email">Donor Email</label>
                <input type="text" class="form-control" id="donor_email" name="donor_email"
                       value="{{ request.args.get('donor_email') or ''}}" placeholder="Email">
            </div>

            <!-- Item Name -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="item_name">Item Name</label>
                <input type="text" class="form-control" id="item_name" name="item_name"
                       value="{{ request.args.get('item_name') or '' }}" placeholder="Item Name">
            </div>

            <!-- Organization Dropdown -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="organization">Organization</label>
                {{ organization_dropdown(request.args.get("organization")) or '' }}
            </div>
            {# TODO pass/set the columns that can be used for sort/filter (i.e. allowed_columns) #}
            {#rv437-29/11/23#}

            <!-- Sort Filter -->
            {% macro sort_filter(cols) %}
            <div class="col">
                <label class="visually-hidden" for="sort">Sort By</label>
                <select class="form-select" id="sort" name="column">
                    {% for col in cols %}
                        {% if col not in ['id', 'organization_id'] %}
                            <option value="{{ col }}">{{ col|replace("_", " ") }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <label class="visually-hidden" for="order">Sort Order</label>
                <select class="form-select" id="order" name="order">
                    <option value="asc">Ascending</option>
                    <option value="desc">Descending</option>
                </select>
            </div>
        {% endmacro %}
        

            <!-- Limit Filter -->
            <div class="col">
                <label class="visually-hidden" for="limit">Limit</label>
                <input type="number" class="form-control" id="limit" name="limit"
                       value="{{ request.args.get('limit', 10) }}" placeholder="Limit">
            </div>

            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <table class="table">
        {% if rows and rows|length > 0 %}
        <thead>
            <tr class="text-capitalize">
                {# generate th tags for each column to display #}
                {# don't show any id or organization_id columns #}
                {# IMPORTANT use table column names as the headings, replace _ with space via filter #}
                {#rv437-29/11/23#}
                {% for col in allowed_columns %}
                    {% if col not in ['id', 'organization_id'] %}
                        <th>{{ col|replace("_", " ") }}</th>
                    {% endif %}
                {% endfor %}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {# generate tr with td tags for each piece of data #}
            {# don't show any id or organization_id columns #}
            {#rv437-29/11/23#}
            
            {% for row in rows %}
                <tr>
                    {% for col in allowed_columns %}
                        {% if col not in ['id', 'organization_id'] %}
                            <td>{{ row[col] }}</td>
                        {% endif %}
                    {% endfor %}
                    <td>
                        <a href="{{ url_for('donations.edit', id=row['id']) }}" class="btn btn-primary">Edit</a>
                        <a href="{{ url_for('donations.delete', id=row['id'], **request.args) }}"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <tbody>
            <tr>
                <td colspan="{{ allowed_columns|length + 1 }}">No results to show</td>
            </tr>
        </tbody>
        {% endif %}
    </table>
</div>
{% endblock %}

MP3/templates/list_organizations.html
{% extends "layout.html" %}
{% block title %}Organization Directory{% endblock %}
{% block content %}
{% from "country_state_selector.html" import country_state_selector %}
{% from "sort_filter.html" import sort_filter %}
<div class="container-fluid">
    <div class="h1 text-center">Organization Directory</div>
    <form method="GET">
        <div class="row">
            {# TODO
                build a horizontal filter/sort form with
                name (show as organization name but name field should be name)
                country/state (provided)
                sort/order (using allowed_columns and provided partial template)
                limit (default 10)
                ensure all fields prefill with request arg data if provided
                #}
            <!-- Organization Name Filter -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="name">Organization Name</label>
                <input type="text" class="form-control" id="name" name="name"
                       value="{{ request.args.get('name') or '' }}" placeholder="Organization Name">
            </div>

            <!-- Country/State Filter -->
            {#rv437-29/11/23#}
            {{ country_state_selector(layout="horizontal") }}

            <!-- Sort Filter -->
            {# TODO pass/set the columns that can be used for sort/filter (i.e. allowed_columns) #}
            {#rv437-29/11/23#}
            {{ sort_filter(cols=allowed_columns) }}

            <!-- Limit Filter -->
            {#rv437-29/11/23#}
            <div class="col">
                <label class="visually-hidden" for="limit">Limit</label>
                <input type="number" class="form-control" id="limit" name="limit"
                       value="{{ request.args.get('limit', 10) }}" placeholder="Limit">
            </div>

            <div class="col">
                <input type="submit" class="btn btn-primary" value="Filter" />
            </div>
            <div class="col">
                <a href="?" class="btn btn-secondary">Reset</a>
            </div>
        </div>
    </form>
    <div class="table-responsive">
        <table class="table">
            {% if rows and rows|length > 0 %}
            <thead>
                <tr class="text-capitalize">
                    {% for col in allowed_columns %}
                        {% if col[0] not in ['id', 'organization_id'] %}
                            <th>{{ col[1]|replace("_", " ") }}</th>
                        {% endif %}
                    {% endfor %}
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {# generate tr with td tags for each piece of data #}
                {# don't show any id or organization_id columns #}
                {#rv437-29/11/23#}
                {# if the td is for website, display it as a link where the text is "website" and the url is the
                website url #}
                {# in the last column add the following
                a view button that passes the organization id to donation search (this will be an organization's donation
                list)
                an edit button that passes the organization id to organization edit
                a delete button that passes the organization id and the request args to the organization delete route
                #}
                <!-- iterate over rows and generate proper tr and td elements with the data -->
                {#rv437-29/11/23#}
                {% for row in rows %}
                    <tr>
                        {% for col in allowed_columns %}
                            {% if col[0] not in ['id', 'organization_id'] %}
                                {% if col == 'website' %}
                                    <td><a href="{{ row[col[0]] }}" target="_blank">Website</a></td>
                                {% else %}
                                    <td>{{ row[col[0]] }}</td>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        <td>
                            <a href="{{ url_for('donations.search', organization_id=row['id']) }}"
                               class="btn btn-primary">View Donations</a>
                            <a href="{{ url_for('organization.edit', id=row['id']) }}"
                               class="btn btn-primary">Edit</a>
                            <a href="{{ url_for('organization.delete', id=row['id'], **request.args) }}"
                               class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            {% else %}
            <tbody>
                <tr>
                    <td colspan="{{ allowed_columns|length + 1 }}">No results to show</td>
                </tr>
            </tbody>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}

MP3/templates/manage_donation.html
{% extends "layout.html" %}
{% block title %}{{ "Edit" if donation.get("id") else "Create" }}
Donation{% endblock %}
{% block content %}
{% from "organization_dropdown.html" import organization_dropdown %}
<div class="container-fluid">
    <div class="h1">{{ "Edit" if donation.get("id") else "Create" }} Donation
    </div>
    <div>
        <form method="POST">
            {#
            generate fields with proper types for the following (keep the name/id attributes the same as the list)
            donor_firstname (required)
            donor_lastname (required)
            donor_email (required)
            item_name (required)
            item_description (optional)
            item_quantity (required) (>0)
            donation_date (required) (mm/dd/yyyy)
            comments (optional)
            organization (provided) (required)
            if a validation error occurs, the inserted form data should persist
            #}
            
            <!--donor first name-->
            {#rv437-29/11/23#}
            <div class="mb-3">
                <label for="donor_firstname" class="form-label">Donor First Name</label>
                <input type="text" class="form-control" id="donor_firstname" name="donor_firstname"
                       value="{{ donation.get('donor_firstname') or ''}}" required>
            </div>

            <!--donor last name-->
            <div class="mb-3">
                <label for="donor_lastname" class="form-label">Donor Last Name</label>
                <input type="text" class="form-control" id="donor_lastname" name="donor_lastname"
                       value="{{ donation.get('donor_lastname') or ''}}" required>
            </div>

            <!--donor email-->
            <div class="mb-3">
                <label for="donor_email" class="form-label">Donor Email</label>
                <input type="email" class="form-control" id="donor_email" name="donor_email"
                       value="{{ donation.get('donor_email') or ''}}" required>
            </div>

            <!--item name-->
            <div class="mb-3">
                <label for="item_name" class="form-label">Item Name</label>
                <input type="text" class="form-control" id="item_name" name="item_name"
                       value="{{ donation.get('item_name') or ''}}" required>
            </div>

            <!--item_description -->
            <div class="mb-3">
                <label for="item_description" class="form-label">Item Description</label>
                <textarea class="form-control" id="item_description" name="item_description"
                          rows="3">{{ donation.get('item_description') or ''}}</textarea>
            </div>

            <!--item_quantity-->
            <div class="mb-3">
                <label for="item_quantity" class="form-label">Item Quantity</label>
                <input type="number" class="form-control" id="item_quantity" name="item_quantity"
                       value="{{ donation.get('item_quantity') or ''}}" required min="1">
            </div>

            <!--donation date-->
            <div class="mb-3">
                <label for="donation_date" class="form-label">Donation Date (mm/dd/yyyy)</label>
                <input type="date" class="form-control" id="donation_date" name="donation_date"
                       value="{{ donation.get('donation_date') or ''}}" required>
            </div>
            <!--comments-->
            <div class="mb-3">
                <label for="comments" class="form-label">Comments</label>
                <input type="text" class="form-control" id="comments" name="comments"
                       value="{{ donation.get('comments') or ''}}" required>
            </div>
            <!-- organization selection-->
           {#rv437-29/11/23#}
            <div class="mb-3">
                <label for="organization_id" class="form-label">Organization</label>
            {{ organization_dropdown(val=donation.get("organization_id")) }}
            </div>
            <input type="submit" class="btn btn-primary"
                value="Save Donation" />

        </form>
    </div>
</div>
{% endblock %}

MP3/templates/nav.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        {# TODO replace my ucid mt85 with your ucid in the below a tag #}
        {#rv437-29/11/23#}
        <a class="navbar-brand" href="{{ url_for('home.index') }}">TD-rv437</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {# TODO: Fill in the relevant hrefs using url_for() #}
        {#rv437-29/11/23#}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- Organization dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Organization
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('organization.search') }}">Search</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('organization.add') }}">Add</a></li>
                    </ul>
                </li>
                <!-- Donation dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Donation
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('donations.search') }}">Search</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('donations.add') }}">Add</a></li>
                    </ul>
                </li>
                <!-- Admin dropdown nav -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Admin
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('admin.importCSV') }}">Import</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>